export const title = 'Login to your Account'
export const buttonText = 'Login'
export const emailLabel = 'Email Address'
export const emailPlaceholder = 'Enter email'
export const passwordLabel = 'Password'
export const passwordPlaceholder = 'Password'
